base:
  config:
    tidb:
      hostname: tidb.funtl.com
      port: 4000
    nacos:
      hostname: nacos.funtl.com
      port: 80

spring:
  application:
    name: ums-admin-login-log-provider
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${base.config.tidb.hostname}:${base.config.tidb.port}/mplus_ums_admin_login_log?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password:
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

dubbo:
  scan:
    base-packages: com.funtl.myshop.plus.provider.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}

mybatis:
  type-aliases-package: com.funtl.myshop.plus.provider.domain
  mapper-locations: classpath:mapper/*.xml